### ISSUE TITLE
What are some actual use cases?

### ISSUE THREAD

**Issue by jgrosso** [louthy/csharp-monad#15]
Yeah, this is by far the coolest thing I've ever seen anyone do with C# (massive kudos on the named parameters to emulate case/match syntax), but when would you really consider using it instead of a more traditional solution? If you want monads this bad, just switch to Haskell!

**Comment by louthy** [comment]
> What are some actual use cases?
Massively open question.  That would be like asking someone who programmed in a language that didn't support if/then/else why they implemented a function called `if` that took a 3 higher-order functions: a predicate and two maps.  It's a pattern like any other language construct.  

C# has first class support and grammar for monads, so this project makes use of it.

> but when would you really consider using it instead of a more traditional solution?
It's to facilitate functional/expression-based programming in C#.

Check my other project for a much more in-depth discussion on why: https://github.com/louthy/language-ext

> If you want monads this bad, just switch to Haskell!
Have you considered that isn't necessarily an option for many people?  I use Haskell, but I also maintain a 5 million line C# application.  There are implementations of monads in many languages (although very few have language constructs to support them like C#); monads don't belong to Haskell.

**Comment by jgrosso** [comment]
There's monads which aren't necessary, though, like State, Writer, IO and all that. Why constrain side effects in an imperative language? You're using C#, so you might as well use it to its fullest; if you don't want side effects, don't use C#.
I do agree that the other monads (like Option and Either) are still helpful.

**Comment by louthy** [comment]
I wrote this library and Language-Ext for those people that understand that imperative programs are inherently less predictable and more error prone.  I don't use the state monad a lot, but where I have used it, it's been very successful.  A simple example would be that for my work project I developed a virtual dom system that could run on the server.  Each 'element' (div, input, etc.) is a function that takes a state value and returns a tuple of `DomElement` and a new state - i.e. a state monad.  It allows us to have chunks of Dom computations that can be composed and can be modified based on state.  Of course I could have done it with a context object, but it would have been an ugly and more error prone solution.

I have also used it for stateful but transactional behaviour; which isn't trivial with imperative constructs.

Side effects are dangerous, and as the project I am working on has got larger and larger I have seen the pain points first hand.  OO worked very well for a while, but it's cognitively very difficult [when a project becomes very large] to understand all of the implications of the changes you're making.  Expression based programming gives much stronger guarantees, and that's why it's useful.

**Comment by WozSoftware** [comment]
@jgrosso - As a recent convert to functional myself, as in last couple of years, I find there is a use for many of the monads even in languages like C#. In fact my C# code has become more functional and less imperative because as louthy states, it is just easier to reason about. I was really hoping the record types would make c#6 but they were dropped for the time being.

Side effects are just a pain and as a project reaches large scale with a team on it the less imperative it is the better. I makes it easier to reason about and maintain. There is less chance someone misses something and breaks things because some less visited piece of code changes state in a stupid way because someone got sloppy.

C# has been moving more and more to a functional language and this is a good thing. It is hard to think functionally for many OO developers as OO is so ingrained but I am slowly pushing the people I work with in this direction as it just makes sense. 

Yes C# started OO but ever since Lambda, closures and Linq made the spec there have been choices and this is letting people see these other routes.

@louthy - Sorry to jump in but looked an interesting discussion :)

**Comment by jgrosso** [comment]
@WozSoftware So you're mentioning record types, immutable state, and all that, but still wanting an OO language to become a functional one? Use F# in that case (it has monads in "computational contexts"). Are you proposing C# become the Scala of .NET? (Maybe there should be a new language, based off of C#, for that, but this would be like removing Java entirely).

**Comment by louthy** [comment]
@jgrosso Rather than trolling us with spurious statements like 'just use F#' (I already dealt with why we would want something like this in C# when you said "Why don't you just use Haskell"), maybe you should lookat the planned features for C# 7:  https://github.com/dotnet/roslyn/issues/2136

I am not entirely sure why you have an issue with others trying to bring functional concepts to C# (especially when it has first-class support for monads, lambdas, etc.).  Nobody is forcing you to use C# or any of these libraries.

**Comment by jgrosso** [comment]
@louth I'm not trolling or anything, and I love the functional features. I
just thought that this might be slightly overboard when there's a language
that did it for you already with great interoperability. Like I said, it's
genius, just maybe a bit impractical.

**Comment by louthy** [comment]
@jgrosso If you were to strip away the core libraries from F# and you just look at the language features itself you will see that it has as many OO features as it has functional (probably more OO because it's a fundamentally more complex paradigm).  

It is the core libraries that make it a 'functional first' platform.  C# is clearly gaining more and more functional features as every release passes, and the new proposed language features are there to aid that process more.  It is likely to end up looking a lot like Scala (but with hopefully less of the grammatical boilerplate).  

Libraries like this, my more complete functional framework [Language-Ext](https://github.com/louthy/language-ext), and Rx.NET are needed to support the language features coming through.  It is almost certainly too difficult for Microsoft to present an alternative functional version of the BCL, and so it's up to the community to do it.

> just thought that this might be slightly overboard when there's a language
that did it for you already with great interoperability. 

In the real world, where there's legacy code to deal with - legacy code that works; there aren't always the opportunities to switch language.  My company that I started has a product with over 5 million lines of C# code, it represents 10 years work.  We now using F# where we can, but you can't just re-write 10 years of work.  

I have come to the conclusion that to build on a project as large and as complex as the C# project I work on, I have to come up with better strategies for dealing with the complexity problem.  A lot of that complexity (I believe) comes from the OO/imperative/in-place-state-update world.  Others may disagree, but that's why this library and [Language-Ext](https://github.com/louthy/language-ext) exists: to tame a language that we *have* to use.  I suspect there are many others in that situation and I find it strange that I have to justify why I developed something and gave it to the world for free.

**Comment by jgrosso** [comment]
@louthy Fair enough.

Thank you,
Blessings,

Joshua Grosso
