### ISSUE TITLE
State monad with modify & gets helpers

### ISSUE THREAD

**Issue by stefc** [louthy/csharp-monad#21]
I really like your simple C# State monad!!! 

How I can enhance it with the both helper functions 'modify' & 'gets' which I see in the Haskell variant ? Can you implement it also on your code ? That's would be very smart. 

The helpers are simple variations of these primitives:

```haskell
modify :: (s -> s) -> State s ()
modify f = do { x <- get; put (f x) }

gets :: (s -> a) -> State s a
gets f = do { x <- get; return (f x) } 
```

At this time I have to call SelectMany twice for get & put the state. In the following code I want to call only one SelectMany with a `State.Modify` helper method. How can we archive that 

```c#
public void StateConstructTest() 
{
    var sm = State.Return<string,int>(10)
         .SelectMany( x => State.Get<string>(), (v, s) => (v, s))
         .SelectMany( x => State.Put("Hello " + (x.v * 10) + x.s ), ( (a,_) => a.s ));
    var res = sm(", World");
    Assert.True(res.State == "Hello 100, World");
} 
```

**Comment by louthy** [comment]
I would advise using my other project language-ext, which is a more complete functional framework for C# - I’m not supporting this library any more.  It has the full set of functions for the State monad in [its Prelude](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/State/State.Prelude.cs):

Also, it’s much easier to use LINQ instead of SelectMany:
```c#
    using LanguageExt.Prelude;
    
    var sm = from x in State<string, int>(10)
             from _ in modify(s => "Hello {x * 10}{s}")
             select unit;

```

**Comment by stefc** [comment]
I'll have a look on Prelude! 

I use `SelectMany` because I want to build the sm within a Aggregate, but I can check if I can also use Linq inside a delegate.
